### ISSUE TITLE
Liquid error: undefined method `downcase’ for nil:NilClass

### ISSUE THREAD

**Issue by ilieghiciuc** [ryanburnette/jekyll-embedly-plugin#1]
Hi Ryan,

I am trying to use your plugin for my website. I've followed the steps to install it but when I try to use it in a post I get this error in the generated page:

Liquid error: undefined method `downcase’ for nil:NilClass

Any chance you could point me in the right direction?

Thank you,
Ilie

**Comment by ryanburnette** [comment]
Try using the edit I just put in the `downcase-issue` branch. Here's what you add to your `Gemfile` to directly reference a branch.

```
gem 'jekyll-embedly-plugin', :git => 'https://github.com/ryanburnette/jekyll-embedly-plugin.git', :branch => 'downcase-issue'
```

**Comment by ryanburnette** [comment]
I'm super busy right now and I'm not actually using Jekyll anymore, so if it's not working you may have to dig into it. I'd be glad to pass this plugin off to someone else's care.

**Comment by ilieghiciuc** [comment]
Hi Ryan,

I am happy to report that it worked. Thank you for the detailed instructions.

Unfortunately I cannot take over since I am only a manager and don’t know any Ruby :) 
The extent of my skill is to patch things together from copy-pastes :)

Thank you very much for your assistance.

Kind regards,

Ilie Ghiciuc | Founder & Manager | Thinslices | +40 748 12 68 67

**Comment by ryanburnette** [comment]
I'll merge that into master as `v0.3.1`. No problem.
